### PR TITLE
LearningSite - remove required from many fields

### PR DESCRIPTION
**Pull request by sdreher**
These records are designed to be fragmentary, with data added over time.

### CODE REVIEW

**Comment by nikolas** [comment]
The migration merged here is causing an error for me:

```
Running migrations:
  Applying main.0002_learning_site_required_fields...Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nik/src/d/writlarge/ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/nik/src/d/writlarge/ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nik/src/d/writlarge/ve/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nik/src/d/writlarge/ve/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/nik/src/d/writlarge/ve/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/home/nik/src/d/writlarge/ve/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/nik/src/d/writlarge/ve/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/nik/src/d/writlarge/ve/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/nik/src/d/writlarge/ve/lib/python3.6/site-packages/django/db/migrations/migration.py", line 112, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/home/nik/src/d/writlarge/ve/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 196, in state_forwards
    state.models[app_label, self.model_name_lower].fields
KeyError: ('main', 'learningsite')
```

My learningsite table is empty - @sdreher this didn't happen on your system?

**Comment by nikolas** [comment]
Hmmm, my error might be related to the squashed migration. (https://stackoverflow.com/a/48082377/173630) I'm investigating.

**Comment by nikolas** [comment]
Alright, well dropping the database and creating it again solved my problem.

**Comment by sdreher** [comment]
Ai - sorry just seeing this. Very likely to do with the squashed migrations.

**Pull request merged**
